const RestaurantTable = [
    {
        id: 1,
        restaurantName: "The Gourmet Spot",
        restaurantType: "Italian",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Blocked",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    },
    {
        id: 2,
        restaurantName: "Sushi Heaven",
        restaurantType: "Japanese",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Pending",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    },
    {
        id: 3,
        restaurantName: "Urban Bites",
        restaurantType: "Japanese",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Active",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    },
    {
        id: 4,
        restaurantName: "Spice Villa",
        restaurantType: "American",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Blocked",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    },
    {
        id: 5,
        restaurantName: "The Gourmet Spot",
        restaurantType: "Italian",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Active",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    },
    {
        id: 6,
        restaurantName: "Sushi Heaven",
        restaurantType: "Japanese",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Active",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    }
    ,
    {
        id: 7,
        restaurantName: "Sushi Heaven",
        restaurantType: "Japanese",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Active",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    }
    ,
    {
        id: 8,
        restaurantName: "Sushi Heaven",
        restaurantType: "Japanese",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Pending",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    }
    ,
    {
        id: 9,
        restaurantName: "Sushi Heaven",
        restaurantType: "Japanese",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Active",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    },
    {
        id: 10,
        restaurantName: "Sushi Heaven",
        restaurantType: "Japanese",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Active",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    },
    {
        id: 11,
        restaurantName: "Sushi Heaven",
        restaurantType: "Japanese",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Active",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    },
    {
        id: 12,
        restaurantName: "Sushi Heaven",
        restaurantType: "Japanese",
        restaurantEmail: "Johandoe@gmail.com",
        restaurantContact: "+1 (305) 123-4567",
        rating: 4.8,
        reviews: 125,
        status: "Active",
        restaurantLocation: "123 Seaside Avenue, Miami, FL, USA",
        restaurantOnboardModel: "Order-Based",
        restaurantCommissionPricing: "Auto-calculated",
        restaurantCompliance: "Hygiene and safety regulations"
    }
];

export default RestaurantTable;